Adds PlusOneBackupSelector to RAMCloud
BeStateless/RAMCloud pull request #20
Opened 2019-09-27 00:10 UTC by OferMania

This gives us deterministic selection for the backupServerId, independent of the replicationId.
We also add test_backup_server.py with Fault Tolerance tests for when a backup server goes down with PlusOneBackup enabled.

2019-10-01 17:11 UTC, vexingcodes requested changes
Looks good, just minor comments.

2019-10-01 17:11 UTC, vexingcodes commented on patches/plus_one.patch
> +     if (useMinCopysets) {
Probably good to do some config-checking here.

```
if (useMinCopysets && usePlusOneBackup) {
    throw std::invalid_argument(
        "Can only use one of min-copysets and plus-one backup strategies, but both were specified.");
}
```

2019-10-01 17:11 UTC, vexingcodes commented on patches/plus_one.patch
> ++    ServerId selectSecondary(uint32_t numBackups, const ServerId backupIds[]);
Add the `virtual` and/or `override` keywords to this function declaration.

2019-10-01 17:11 UTC, vexingcodes commented on patches/plus_one.patch
> ++/* Copyright (c) 2009-2016 Stanford University
2019 is the current year. I have no idea how copyright statements work though. I don't know if we should just omit this entirely on files that we create? :man_shrugging:

2019-10-01 20:27 UTC, OferMania commented on patches/plus_one.patch
> ++    ServerId selectSecondary(uint32_t numBackups, const ServerId backupIds[]);
recommended c++11 convention is to use just `override`, so I'm sticking with that.

2019-10-01 20:27 UTC, OferMania commented on patches/plus_one.patch
> ++/* Copyright (c) 2009-2016 Stanford University
I'm not sure either, but will change date to 2019 for now. When I submit for RAMCloud code review, we can find out at that point. I doubt it matters for a patchset internal to us.

2019-10-01 20:27 UTC, OferMania commented on patches/plus_one.patch
> +     if (useMinCopysets) {
Will add

2019-10-03 16:12 UTC, vexingcodes approved these changes
Looks good!

2019-10-03 20:39 UTC, merged